In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
### sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9839, 5024, 4225, 7458],
 [9839, 5024, 4225, 6927],
 [9839, 8969, 4225, 7941],
 [3376, 2453, 9669, 3874, 3342],
 [3376, 2453, 9669, 3874, 4096],
 [8764, 9839, 2675, 4225, 7809],
 [8866, 6915, 620, 3874]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9839 5024 4225 7458]
 [   0    0    0    0 9839 5024 4225 6927]
 [   0    0    0    0 9839 8969 4225 7941]
 [   0    0    0 3376 2453 9669 3874 3342]
 [   0    0    0 3376 2453 9669 3874 4096]
 [   0    0    0 8764 9839 2675 4225 7809]
 [   0    0    0    0 8866 6915  620 3874]]


In [11]:
## feature representation
dim=10

In [12]:
# now we will create our embedding layer
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
#here every word is kinda represented in 10 dimensions
model.predict(embedded_docs)

1/1 [==============================] - 1s 557ms/step


array([[[ 0.00901599, -0.03958514, -0.04586252, -0.00942874,
         -0.01931193,  0.00013349, -0.00359422,  0.03745332,
          0.02729977, -0.00926416],
        [ 0.00901599, -0.03958514, -0.04586252, -0.00942874,
         -0.01931193,  0.00013349, -0.00359422,  0.03745332,
          0.02729977, -0.00926416],
        [ 0.00901599, -0.03958514, -0.04586252, -0.00942874,
         -0.01931193,  0.00013349, -0.00359422,  0.03745332,
          0.02729977, -0.00926416],
        [ 0.00901599, -0.03958514, -0.04586252, -0.00942874,
         -0.01931193,  0.00013349, -0.00359422,  0.03745332,
          0.02729977, -0.00926416],
        [-0.03958422,  0.01318921, -0.0400582 , -0.04243606,
         -0.0070494 , -0.03136905,  0.01997611, -0.04076196,
         -0.00575791, -0.01395935],
        [ 0.04523313,  0.04463962,  0.01796785, -0.03525407,
         -0.01308946,  0.03311649, -0.0194549 ,  0.02909927,
         -0.00740778, -0.04875466],
        [-0.03246545, -0.0438136 ,  0.01089426, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9839, 5024, 4225, 7458])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 96ms/step


array([[ 0.00901599, -0.03958514, -0.04586252, -0.00942874, -0.01931193,
         0.00013349, -0.00359422,  0.03745332,  0.02729977, -0.00926416],
       [ 0.00901599, -0.03958514, -0.04586252, -0.00942874, -0.01931193,
         0.00013349, -0.00359422,  0.03745332,  0.02729977, -0.00926416],
       [ 0.00901599, -0.03958514, -0.04586252, -0.00942874, -0.01931193,
         0.00013349, -0.00359422,  0.03745332,  0.02729977, -0.00926416],
       [ 0.00901599, -0.03958514, -0.04586252, -0.00942874, -0.01931193,
         0.00013349, -0.00359422,  0.03745332,  0.02729977, -0.00926416],
       [-0.03958422,  0.01318921, -0.0400582 , -0.04243606, -0.0070494 ,
        -0.03136905,  0.01997611, -0.04076196, -0.00575791, -0.01395935],
       [ 0.04523313,  0.04463962,  0.01796785, -0.03525407, -0.01308946,
         0.03311649, -0.0194549 ,  0.02909927, -0.00740778, -0.04875466],
       [-0.03246545, -0.0438136 ,  0.01089426, -0.00743542,  0.02808383,
        -0.03373917, -0.04918573,  0.03947601